version: '0.0.1'
services:
  api:
    build:
      context: "./something_server"
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./something_server:/something_server
      - ${ENVIRONMENT}_bundle:/usr/local/bundle
volumes:
    dev_pg:
    prod_pg:
    dev_bundle:
    prod_bundle: