version: '0.0.1'
services:
  pg:
    image: "postgres:15.1"
    restart: on-failure
    env_file: ".env"
    environment:
      - POSTGRES_USER=${DBU}
      - POSTGRES_PASSWORD=${DBP}
    volumes:
      - "${ENVIRONMENT}_pg:/var/lib/psql/"
      - "${ENVIRONMENT}_pg:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
  api:
    build:
      context: "./something_server"
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DBU=${DBU}
      - DBP=${DBP}
      - DBH=${DBH}
      - DBHP=${DBHP}
      - DBA=${DBA}
      - AUTH_SECRET=${AUTH_SECRET}
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "4000:4000"
    volumes:
      - ./something_server:/something_server
      - ${ENVIRONMENT}_bundle:/usr/local/bundle
    depends_on:
      - pg
    links:
      - pg
  client:
    build:
      context: "./something_client"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./something_client:/something_client
      - ${ENVIRONMENT}_node_modules:/something_client/node_modules
    depends_on:
      - api
      - pg
    links:
      - api
volumes:
    dev_pg:
    prod_pg:
    dev_bundle:
    prod_bundle:
    dev_node_modules:
    prod_node_modules: